language: python

python:
    - 2.7

notifications:
  email: false

sudo: required

install:
    - pip install --upgrade pip
    - pip install geonames
    - pip install pygeocoder
    - pip install python-lxml

script:
    - python noaaweb/noaaweb.py noaaweb/samplein.csv noaaweb/sampleout.csv







