build: false

environment:
  NCDC_TOKEN: YcnZInRPxWnyyDEvysQNaTHrtgMEMHZD
  matrix:
    - PYTHON: "C:\\Python27"
      PYTHON_VERSION: "2.7.8"
      PYTHON_ARCH: "32"

init:
  - "ECHO %PYTHON% %PYTHON_VERSION% %PYTHON_ARCH%"

install:
  - "%PYTHON%/Scripts/pip.exe install ."
  - "%PYTHON%/Scripts/pip.exe install -r requirements.txt"

test_script:
  - "%PYTHON%/Scripts/nosetests"
#---------------------------------#
